[package]
name = "axum_prime"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.6.9"
serde = { version = "1.0.228", features = ["serde_derive"] }
tokio = { version = "1", features = ["full"] }
